export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_CATEGORY = 'SET_CATEGORY';

export const UPDATE_SURVEY_RESULT = 'UPDATE_SURVEY_RESULT';
export const RESET_SURVEY_RESULT = 'RESET_SURVEY_RESULT';
